# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('destination_date', models.DateTimeField()),
                ('step_size', models.IntegerField(help_text='Step size in minutes. The Tardis will take us to our destination stopping at intervals to execute any callbacksthat are defined for our trips.')),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
