# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tardis', '0004_auto_20160521_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTravel',
            new_name='Trip',
        ),
    ]
