# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis', '0002_auto_20160521_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetravel',
            old_name='d_auto_now_add',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='timetravel',
            name='d_auto_created',
        ),
        migrations.RemoveField(
            model_name='timetravel',
            name='d_auto_now',
        ),
        migrations.AddField(
            model_name='timetravel',
            name='destination_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 21, 19, 47, 23, 179935)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetravel',
            name='step_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
