# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tardis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetravel',
            name='d_auto_created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetravel',
            name='d_auto_now',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
